import { chromium } from '@playwright/test';
import { readFile } from 'node:fs/promises';
const svg = await readFile(new URL('../assets/mark.svg', import.meta.url), 'utf8');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1024, height: 1024 }, deviceScaleFactor: 1 });
await page.setContent(`<style>html,body{margin:0}svg{display:block;width:100vw;height:100vh}</style>${svg}`);
await page.screenshot({ path: new URL('../assets/icon.png', import.meta.url).pathname, omitBackground: true });
await page.setViewportSize({ width: 64, height: 64 });
await page.screenshot({ path: new URL('../assets/favicon.png', import.meta.url).pathname, omitBackground: true });
await browser.close();
