import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Platform, ScrollView, Text, View } from 'react-native';
import { api, Message, Report } from './api';
import { Button, C, Field, Icon, Notice, s } from './ui';
import { RewardControls } from './Rewards';

export default function Conversation({ id, token, finder = false, onResolved }: { id: string; token: string; finder?: boolean; onResolved?: () => void }) {
  const [report, setReport] = useState<Report>(); const [messages, setMessages] = useState<Message[]>([]); const [body, setBody] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState(false); const [canResolve, setCanResolve] = useState(false);
  const scroll = useRef<ScrollView>(null); const generation = useRef(0);
  const path = finder ? `/finder/reports/${id}` : `/reports/${id}`;
  useEffect(() => { let live = true; let fetching = false; setCanResolve(false); setReport(undefined); setMessages([]); setBody(''); setConfirm(false); setBusy(false); setError(''); const current = ++generation.current; async function load() { if (fetching) return; fetching = true; try { const data = await api<{ report: Report; messages: Message[] }>(path, token); if (live && current === generation.current) { setReport(data.report); setMessages(data.messages); setError(''); } } catch(e) { if (live) setError((e as Error).message); } finally { fetching = false; } } load(); const timer = setInterval(load, 4000); return () => { live = false; generation.current++; clearInterval(timer); }; }, [path, token]);
  async function send() { if (!body.trim() || busy) return; setBusy(true); setError(''); const draft = body.trim(); const current = generation.current; try { const { message } = await api<{ message: Message }>(`${path}/messages`, token, { body: draft }); if (current === generation.current) { setMessages(prev => prev.some(m => m.id === message.id) ? prev : [...prev, message]); setBody(''); } } catch(e) { if (current === generation.current) setError((e as Error).message); } finally { if (current === generation.current) setBusy(false); } }
  async function resolve() { if (!canResolve || busy) return; setBusy(true); setError(''); const current = generation.current; try { const result = await api<{ report: Report }>(`${path}/resolve`, token, {}); if (current === generation.current) { setReport(result.report); setConfirm(false); onResolved?.(); } } catch(e) { if (current === generation.current) setError((e as Error).message); } finally { if (current === generation.current) setBusy(false); } }
  return <View style={{ flex: 1, gap: 18, minHeight: 440 }}>
    <View style={[s.between, { flexWrap: 'wrap' }]}><View style={{ gap: 6 }}><Text style={s.h3}>{report?.tagName || 'Conversa privada'}</Text><Text style={s.small}>{finder ? 'Você está falando com o dono.' : `Com ${report?.finderName || 'quem encontrou'}`}</Text></View><View style={[s.row, { backgroundColor: C.soft, padding: 8, borderRadius: 9 }]}><Icon name="shield" size={13} color={C.purple} /><Text style={{ color: C.purple, fontSize: 11 }}>Contatos protegidos</Text></View></View>
    {!!error && <Notice error text={error} />}
    {!report && !error ? <ActivityIndicator color={C.purple} /> : null}
    {finder && <Text style={s.small}>{Platform.OS === 'web' ? 'Volte a este link neste navegador para ver a resposta. O acesso fica salvo por 30 dias; limpar os dados do site remove a conversa deste aparelho.' : 'Escaneie a etiqueta novamente para voltar à conversa neste aplicativo. Apagar os dados do aplicativo remove o acesso salvo neste aparelho.'}</Text>}
    <ScrollView ref={scroll} style={{ maxHeight: 400, minHeight: 200, backgroundColor: C.bg, borderRadius: 15 }} contentContainerStyle={{ padding: 15, gap: 14 }} onContentSizeChange={() => scroll.current?.scrollToEnd({ animated: false })}>
      {messages.map(message => { const own = message.role === (finder ? 'finder' : 'owner'); return <View key={message.id} style={{ alignSelf: own ? 'flex-end' : 'flex-start', maxWidth: '88%', gap: 5 }}><View style={{ backgroundColor: own ? C.purple : C.raised, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 16, borderBottomRightRadius: own ? 4 : 16, borderBottomLeftRadius: own ? 16 : 4 }}><Text style={{ color: own ? C.onAccent : C.ink, fontSize: 14, lineHeight: 22 }}>{message.body}</Text></View><Text style={[s.small, { fontSize: 10, alignSelf: own ? 'flex-end' : 'flex-start' }]}>{own ? 'Você' : message.role === 'owner' ? 'Dono' : report?.finderName || 'Quem encontrou'} · {new Date(message.createdAt).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</Text></View>; })}
    </ScrollView>
    {report ? <RewardControls key={`${path}:${token}`} reportId={id} token={token} finder={finder} closed={report.status === 'resolved'} onCanResolve={setCanResolve} /> : null}
    {report?.status === 'resolved' ? <Notice text="Devolução confirmada. Obrigado por fazer parte deste reencontro!" /> : report ? <><Field label="Mensagem" value={body} onChangeText={setBody} placeholder="Combine um lugar público para a entrega…" multiline maxLength={2000} /><Button onPress={send} icon="send" busy={busy} disabled={!body.trim()}>Enviar</Button>{!finder && (confirm ? <View style={{ gap: 12 }}><Text style={s.body}>O objeto já está com você? A confirmação encerra todas as conversas abertas sobre este objeto e marca o objeto como protegido.</Text><Button onPress={resolve} busy={busy} disabled={!canResolve} icon="check">Sim, recebi meu objeto</Button><Button variant="ghost" onPress={() => setConfirm(false)}>Ainda não</Button></View> : <Button variant="secondary" onPress={() => setConfirm(true)} disabled={!canResolve || busy} icon="check-circle">Confirmar devolução</Button>)}</> : null}
  </View>;
}
