import React, { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { api, Tag } from './api';
import { Button, categories, C, Field, Icon, Notice, Sheet, s } from './ui';

export default function TagForm({ token, tag, onClose, onSaved }: { token: string; tag?: Tag; onClose: () => void; onSaved: (tag: Tag) => void }) {
  const [name, setName] = useState(tag?.name || ''); const [category, setCategory] = useState(categories.some(c => c.name === tag?.category) ? tag!.category : tag ? 'Outro' : 'Mochila'); const [description, setDescription] = useState(tag?.description || ''); const [publicMessage, setPublicMessage] = useState(tag?.publicMessage || 'Obrigado por cuidar do que é importante para mim. Me envie uma mensagem para combinarmos a devolução.');
  const [reward, setReward] = useState(tag?.rewardAmount ? String(tag.rewardAmount) : ''); const [currency, setCurrency] = useState(tag?.rewardCurrency || 'BRL'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function save() { if (!name.trim()) { setError('Dê um nome ao objeto.'); return; } const amount = reward.trim() ? Number(reward.replace(',', '.')) : 0; if (!Number.isFinite(amount) || amount < 0 || amount > 100000) { setError('Informe uma recompensa entre 0 e 100.000.'); return; } setBusy(true); setError(''); try { const { tag: saved } = await api<{ tag: Tag }>(tag ? `/tags/${tag.id}` : '/tags', token, { name: name.trim(), category, color: categories.find(c => c.name === category)?.color || categories[5].color, description, publicMessage, rewardAmount: amount, rewardCurrency: currency }, tag ? 'PATCH' : 'POST'); onSaved(saved); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Sheet title={tag ? 'Editar objeto' : 'Um novo objeto protegido'} onClose={onClose}>
    {!!error && <Notice error text={error} />}
    <Field label="Nome do objeto" placeholder="Ex.: Minha mochila verde" value={name} onChangeText={setName} maxLength={80} autoFocus />
    <View style={{ gap: 10 }}><Text style={s.label}>Categoria</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 9 }}>{categories.map(c => <Pressable key={c.name} accessibilityRole="button" accessibilityLabel={c.name} accessibilityState={{ selected: c.name === category }} onPress={() => setCategory(c.name)} style={{ flexDirection: 'row', gap: 7, paddingHorizontal: 12, minHeight: 43, alignItems: 'center', borderWidth: 1, borderRadius: 11, backgroundColor: c.name === category ? C.soft : C.surface, borderColor: c.name === category ? C.purple : C.line }}><Icon name={c.icon} size={16} color={c.name === category ? C.purple : C.muted} /><Text style={{ color: c.name === category ? C.purple : C.ink, fontSize: 12 }}>{c.name}</Text></Pressable>)}</View></View>
    <Field label="Anotação particular (opcional)" placeholder="Modelo, cor ou um detalhe para lembrar" value={description} onChangeText={setDescription} maxLength={500} help="Só você vê esta anotação." />
    <Field label="Mensagem na etiqueta" multiline value={publicMessage} onChangeText={setPublicMessage} maxLength={500} help="Quem escanear o QR verá esta mensagem. Evite colocar telefone ou endereço." />
    <View style={s.divider} /><View style={{ gap: 13 }}><View style={s.row}><Icon name="gift" color={C.purple} /><Text style={s.h3}>Um agradecimento opcional</Text></View><Text style={s.small}>Você pode oferecer uma recompensa e combinar o pagamento na conversa. Este valor é uma promessa: nenhum dinheiro é depositado ou transferido pelo app.</Text><Field label="Valor da recompensa (opcional)" value={reward} onChangeText={setReward} keyboardType="decimal-pad" placeholder="0,00" maxLength={12} /><View style={s.row}>{['BRL', 'USDC', 'SKR'].map(c => <Button key={c} variant={c === currency ? 'primary' : 'secondary'} onPress={() => setCurrency(c)}>{c === 'BRL' ? 'R$' : c}</Button>)}</View></View>
    <Button onPress={save} busy={busy} icon={tag ? 'check' : 'plus'}>{tag ? 'Salvar alterações' : 'Criar etiqueta'}</Button>
  </Sheet>;
}
