import React, { PropsWithChildren, useEffect, useState } from 'react';
import { AccessibilityInfo, ActivityIndicator, Keyboard, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, TextInputProps, View, ViewStyle } from 'react-native';
import Feather from '@expo/vector-icons/Feather';

// Orkest dark foundations, converted from its OKLCH tokens for React Native.
// Secondary text is slightly brighter to remain legible at mobile text sizes.
export const C = {
  bg: '#090910', surface: '#0F0F15', popover: '#15151B', raised: '#212126',
  ink: '#E7E7EB', muted: '#97979E', line: '#292830',
  purple: '#C4A1FF', onAccent: '#0C0A12', soft: '#231C32',
  amber: '#E9BA79', amberSoft: '#30251A',
  red: '#F099A2', redSoft: '#301D25', redLine: '#53313C',
};
export type IconName = React.ComponentProps<typeof Feather>['name'];
export const Icon = ({ name, size = 20, color = C.ink }: { name: IconName; size?: number; color?: string }) => <Feather name={name} size={size} color={color} aria-hidden={true} accessible={false} accessibilityElementsHidden importantForAccessibility="no-hide-descendants" />;
export function Brand() { return <View style={s.row}><View style={s.brandMark}><Icon name="crosshair" color={C.onAccent} size={22} /></View><Text style={s.brand}>seeker<Text style={{ fontWeight: '400' }}>tag</Text><Text style={{ color: C.purple }}>.</Text></Text></View>; }
export function Button({ children, onPress, icon, variant = 'primary', busy = false, disabled = false, style, label, expanded }: PropsWithChildren<{ onPress: () => void; icon?: IconName; variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; busy?: boolean; disabled?: boolean; style?: ViewStyle; label?: string; expanded?: boolean }>) { const color = variant === 'primary' ? C.onAccent : variant === 'danger' ? C.red : C.ink; return <Pressable accessibilityRole="button" accessibilityLabel={label || (typeof children === 'string' ? children : undefined)} accessibilityState={{ disabled: busy || disabled, busy, expanded }} disabled={busy || disabled} onPress={onPress} style={({ pressed }) => [s.button, variant === 'primary' ? { backgroundColor: C.purple } : variant === 'secondary' ? { backgroundColor: C.surface, borderWidth: 1, borderColor: C.line } : variant === 'danger' ? { backgroundColor: C.redSoft } : { backgroundColor: 'transparent' }, (busy || disabled) && { opacity: 0.5 }, pressed && { opacity: 0.8, transform: [{ scale: 0.98 }] }, style]}>{busy ? <ActivityIndicator size="small" color={color} /> : icon ? <Icon name={icon} color={color} size={18} /> : null}{children !== undefined && children !== '' && <Text style={[s.buttonText, { color }]}>{children}</Text>}</Pressable>; }
export function Field({ label, help, ...props }: TextInputProps & { label: string; help?: string }) { return <View style={{ gap: 8 }}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor={C.muted} selectionColor={C.purple} keyboardAppearance="dark" {...props} style={[s.input, props.multiline && { minHeight: 102, textAlignVertical: 'top', paddingTop: 14 }, props.style]} />{help ? <Text style={s.small}>{help}</Text> : null}</View>; }
export function Notice({ text, error = false }: { text: string; error?: boolean }) { return <View accessibilityRole="alert" style={[s.notice, { backgroundColor: error ? C.redSoft : C.soft }]}><Icon name={error ? 'alert-circle' : 'check-circle'} size={18} color={error ? C.red : C.purple} /><Text style={{ color: error ? C.red : C.purple, flex: 1, lineHeight: 21 }}>{text}</Text></View>; }
export function Pill({ status }: { status: TagStatus }) { const info = status === 'lost' ? ['Perdido', C.amber, C.amberSoft] : status === 'paused' ? ['QR pausado', C.muted, C.raised] : ['QR ativo', C.purple, C.soft]; return <View style={[s.pill, { backgroundColor: info[2] }]}><View style={{ height: 5, width: 5, borderRadius: 3, backgroundColor: info[1] }} /><Text style={{ fontSize: 11, fontWeight: '600', color: info[1] }}>{info[0]}</Text></View>; }
type TagStatus = 'active' | 'lost' | 'paused';
export function Sheet({ title, subtitle, onClose, children, dismissible = true, footer }: PropsWithChildren<{ title: string; subtitle?: string; onClose: () => void; dismissible?: boolean; footer?: React.ReactNode }>) {
  const [reducedMotion, setReducedMotion] = useState(false);
  useEffect(() => { let live = true; void AccessibilityInfo.isReduceMotionEnabled().then(value => { if (live) setReducedMotion(value); }); const subscription = AccessibilityInfo.addEventListener('reduceMotionChanged', setReducedMotion); return () => { live = false; subscription.remove(); }; }, []);
  return <Modal transparent visible animationType={reducedMotion ? 'none' : 'fade'} onRequestClose={() => { if (Platform.OS !== 'web' && Keyboard.isVisible()) Keyboard.dismiss(); else if (dismissible) onClose(); }}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : Platform.OS === 'android' ? 'height' : undefined} style={s.overlay}><View role={Platform.OS === 'web' ? 'dialog' : undefined} aria-modal={Platform.OS === 'web' ? true : undefined} accessibilityLabel={title} accessibilityViewIsModal style={s.sheet}><View style={[s.between, { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 14 }]}><View style={{ flex: 1, gap: 6 }}><Text accessibilityRole="header" style={s.h2}>{title}</Text>{subtitle ? <Text style={s.small}>{subtitle}</Text> : null}</View>{dismissible && <Button variant="ghost" onPress={onClose} icon="x" label="Fechar" />}</View><ScrollView style={{ flexShrink: 1 }} keyboardDismissMode="on-drag" keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 20, paddingTop: 4, gap: 18 }}>{children}</ScrollView>{footer ? <View style={{ padding: 20, paddingTop: 14, borderTopWidth: 1, borderColor: C.line, backgroundColor: C.popover }}>{footer}</View> : null}</View></KeyboardAvoidingView></Modal>;
}
export const categories: { name: string; icon: IconName; color: string }[] = [{ name: 'Mochila', icon: 'shopping-bag', color: '#242130' }, { name: 'Mala', icon: 'briefcase', color: '#27222D' }, { name: 'Chaves', icon: 'key', color: '#282039' }, { name: 'Pet', icon: 'heart', color: '#2C202F' }, { name: 'Eletrônico', icon: 'headphones', color: '#202332' }, { name: 'Outro', icon: 'box', color: '#24242B' }];
export const categoryInfo = (name: string) => categories.find(c => c.name === name) || categories[5];
export const formatDate = (date: string) => new Date(date).toLocaleDateString('pt-BR', { day: 'numeric', month: 'short' });
export const s = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, brandMark: { height: 35, width: 35, borderRadius: 12, backgroundColor: C.purple, alignItems: 'center', justifyContent: 'center' }, brand: { color: C.ink, fontSize: 26, fontWeight: '700', letterSpacing: -1.1 },
  button: { minHeight: 46, borderRadius: 12, paddingHorizontal: 17, paddingVertical: 12, flexDirection: 'row', gap: 9, alignItems: 'center', justifyContent: 'center' }, buttonText: { fontSize: 14, fontWeight: '600' },
  label: { color: C.ink, fontSize: 13, fontWeight: '600' }, input: { minHeight: 49, borderWidth: 1, borderColor: C.line, borderRadius: 11, paddingHorizontal: 14, backgroundColor: C.surface, color: C.ink, fontSize: 15, ...(Platform.OS === 'web' ? { outlineColor: C.purple } as any : {}) },
  h1: { color: C.ink, fontSize: 36, fontWeight: '600', letterSpacing: -1.3, lineHeight: 43 }, h2: { color: C.ink, fontSize: 23, fontWeight: '600', letterSpacing: -0.7 }, h3: { color: C.ink, fontSize: 17, fontWeight: '600', letterSpacing: -0.3 }, body: { color: C.muted, fontSize: 15, lineHeight: 24 }, small: { color: C.muted, fontSize: 12, lineHeight: 19 },
  notice: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 14, borderRadius: 12 }, pill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 6, paddingHorizontal: 10, borderRadius: 20 },
  card: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.line, borderRadius: 19, padding: 24 }, divider: { height: 1, backgroundColor: C.line }, overlay: { flex: 1, backgroundColor: '#000000B3', alignItems: 'center', justifyContent: 'center', padding: 16 }, sheet: { width: '100%', maxWidth: 540, maxHeight: '94%', borderRadius: 24, backgroundColor: C.popover, overflow: 'hidden', ...(Platform.OS === 'web' ? { boxShadow: '0 24px 80px #00000099' } : {}) },
  empty: { alignItems: 'center', justifyContent: 'center', padding: 40, gap: 14, minHeight: 270 }, circle: { width: 62, height: 62, borderRadius: 21, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center' },
});
