import React, { PropsWithChildren } from 'react';
import { ActivityIndicator, Keyboard, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, TextInputProps, View, ViewStyle } from 'react-native';
import Feather from '@expo/vector-icons/Feather';

export const C = { bg: '#F8F7F4', white: '#FFFFFF', ink: '#252925', muted: '#6B7068', line: '#E5E6DF', purple: '#6955D8', soft: '#EEEBFB', green: '#307354', greenSoft: '#E7F1E9', amber: '#A05B19', amberSoft: '#FFF0D8', red: '#AD3C3C' };
export type IconName = React.ComponentProps<typeof Feather>['name'];
export const Icon = ({ name, size = 20, color = C.ink }: { name: IconName; size?: number; color?: string }) => <Feather name={name} size={size} color={color} aria-hidden={true} accessible={false} accessibilityElementsHidden importantForAccessibility="no-hide-descendants" />;
export function Brand({ light = false }: { light?: boolean }) { return <View style={s.row}><View style={[s.brandMark, light && { backgroundColor: '#D9EE9B' }]}><Icon name="crosshair" color={light ? C.ink : 'white'} size={22} /></View><Text style={[s.brand, light && { color: 'white' }]}>seeker<Text style={{ fontWeight: '400' }}>tag</Text><Text style={{ color: light ? '#D9EE9B' : C.purple }}>.</Text></Text></View>; }
export function Button({ children, onPress, icon, variant = 'primary', busy = false, disabled = false, style, label }: PropsWithChildren<{ onPress: () => void; icon?: IconName; variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; busy?: boolean; disabled?: boolean; style?: ViewStyle; label?: string }>) { const color = variant === 'primary' ? 'white' : variant === 'danger' ? C.red : C.ink; return <Pressable accessibilityRole="button" accessibilityLabel={label || (typeof children === 'string' ? children : undefined)} disabled={busy || disabled} onPress={onPress} style={({ pressed }) => [s.button, variant === 'primary' ? { backgroundColor: C.purple } : variant === 'secondary' ? { backgroundColor: C.white, borderWidth: 1, borderColor: C.line } : variant === 'danger' ? { backgroundColor: '#FAEBEB' } : { backgroundColor: 'transparent' }, (busy || disabled) && { opacity: 0.5 }, pressed && { opacity: 0.8, transform: [{ scale: 0.98 }] }, style]}>{busy ? <ActivityIndicator size="small" color={color} /> : icon ? <Icon name={icon} color={color} size={18} /> : null}<Text style={[s.buttonText, { color }]}>{children}</Text></Pressable>; }
export function Field({ label, help, ...props }: TextInputProps & { label: string; help?: string }) { return <View style={{ gap: 8 }}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor="#92968D" {...props} style={[s.input, props.multiline && { minHeight: 102, textAlignVertical: 'top', paddingTop: 14 }, props.style]} />{help ? <Text style={s.small}>{help}</Text> : null}</View>; }
export function Notice({ text, error = false }: { text: string; error?: boolean }) { return <View accessibilityRole="alert" style={[s.notice, { backgroundColor: error ? '#FAEBEB' : C.greenSoft }]}><Icon name={error ? 'alert-circle' : 'check-circle'} size={18} color={error ? C.red : C.green} /><Text style={{ color: error ? C.red : C.green, flex: 1, lineHeight: 21 }}>{text}</Text></View>; }
export function Pill({ status }: { status: TagStatus }) { const info = status === 'lost' ? ['Perdido', C.amber, C.amberSoft] : status === 'paused' ? ['Pausado', C.muted, '#EDEEE9'] : ['Protegido', C.green, C.greenSoft]; return <View style={[s.pill, { backgroundColor: info[2] }]}><View style={{ height: 5, width: 5, borderRadius: 3, backgroundColor: info[1] }} /><Text style={{ fontSize: 11, fontWeight: '600', color: info[1] }}>{info[0]}</Text></View>; }
type TagStatus = 'active' | 'lost' | 'paused';
export function Sheet({ title, subtitle, onClose, children, dismissible = true }: PropsWithChildren<{ title: string; subtitle?: string; onClose: () => void; dismissible?: boolean }>) { return <Modal transparent visible animationType="fade" onRequestClose={() => { if (Keyboard.isVisible()) Keyboard.dismiss(); else if (dismissible) onClose(); }}><View style={s.overlay}><View accessibilityViewIsModal style={s.sheet}><View style={[s.between, { paddingHorizontal: 28, paddingTop: 25, paddingBottom: 18 }]}><View style={{ flex: 1, gap: 6 }}><Text accessibilityRole="header" style={s.h2}>{title}</Text>{subtitle ? <Text style={s.small}>{subtitle}</Text> : null}</View>{dismissible && <Button variant="ghost" onPress={onClose} icon="x" label="Fechar" />}</View><ScrollView keyboardDismissMode="on-drag" keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 28, paddingTop: 8, gap: 20 }}>{children}</ScrollView></View></View></Modal>; }
export const categories: { name: string; icon: IconName; color: string }[] = [{ name: 'Mochila', icon: 'shopping-bag', color: '#E6EADA' }, { name: 'Mala', icon: 'briefcase', color: '#F3DFCD' }, { name: 'Chaves', icon: 'key', color: '#E4DFF7' }, { name: 'Pet', icon: 'heart', color: '#F2DFE3' }, { name: 'Eletrônico', icon: 'headphones', color: '#DDE9ED' }, { name: 'Outro', icon: 'box', color: '#EAE6DC' }];
export const categoryInfo = (name: string) => categories.find(c => c.name === name) || categories[5];
export const formatDate = (date: string) => new Date(date).toLocaleDateString('pt-BR', { day: 'numeric', month: 'short' });
export const s = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, brandMark: { height: 35, width: 35, borderRadius: 12, backgroundColor: C.ink, alignItems: 'center', justifyContent: 'center' }, brand: { color: C.ink, fontSize: 26, fontWeight: '700', letterSpacing: -1.1 },
  button: { minHeight: 46, borderRadius: 12, paddingHorizontal: 17, paddingVertical: 12, flexDirection: 'row', gap: 9, alignItems: 'center', justifyContent: 'center' }, buttonText: { fontSize: 14, fontWeight: '600' },
  label: { color: C.ink, fontSize: 13, fontWeight: '600' }, input: { minHeight: 49, borderWidth: 1, borderColor: C.line, borderRadius: 11, paddingHorizontal: 14, backgroundColor: 'white', color: C.ink, fontSize: 15, ...(Platform.OS === 'web' ? { outlineColor: C.purple } as any : {}) },
  h1: { color: C.ink, fontSize: 36, fontWeight: '600', letterSpacing: -1.3, lineHeight: 43 }, h2: { color: C.ink, fontSize: 23, fontWeight: '600', letterSpacing: -0.7 }, h3: { color: C.ink, fontSize: 17, fontWeight: '600', letterSpacing: -0.3 }, body: { color: C.muted, fontSize: 15, lineHeight: 24 }, small: { color: C.muted, fontSize: 12, lineHeight: 19 }, eyebrow: { color: C.muted, fontSize: 10, fontWeight: '700', letterSpacing: 1.6 },
  notice: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 14, borderRadius: 12 }, pill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 6, paddingHorizontal: 10, borderRadius: 20 },
  card: { backgroundColor: 'white', borderWidth: 1, borderColor: C.line, borderRadius: 19, padding: 24 }, divider: { height: 1, backgroundColor: C.line }, overlay: { flex: 1, backgroundColor: '#151B2466', alignItems: 'center', justifyContent: 'center', padding: 16 }, sheet: { width: '100%', maxWidth: 540, maxHeight: '94%', borderRadius: 24, backgroundColor: C.bg, overflow: 'hidden', ...(Platform.OS === 'web' ? { boxShadow: '0 24px 80px #00000022' } : {}) },
  empty: { alignItems: 'center', justifyContent: 'center', padding: 40, gap: 14, minHeight: 270 }, circle: { width: 62, height: 62, borderRadius: 21, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center' },
});
